### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by FirePing32** [metacall/homebrew#3]
There are some ways we can improve the build process in `build.sh`.

- Check if brew is already installed rather than downloading the binary
- Install the recipe without upgrading other brew packages to speed up the installation process (setting `HOMEBREW_NO_AUTO_UPDATE`)
- Remove cmake build cache after installing formula
- Handle error response from brew when kegs are not found 
- Remove `-g` flag, does not exist in brew 
   https://github.com/metacall/homebrew/blob/19faeba299340b7fffc1361dbdf138da09ea688b/build.sh#L19

**Comment by FirePing32** [comment]
cc @AkechiShiro @viferga

**Comment by viferga** [comment]
@FirePing32 cool, feel free to create a PR for solving this.
